version: '2'
services:
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  # app:
  #   extends:
  #     file: app.yml
  #     service: app
  # appslave:
  #   extends:
  #     file: appslave.yml
  #     service: appslave
  mysql:
    extends:
      file: mysql.yml
      service: mysql
  adminer:
    extends:
      file: mysql.yml
      service: adminer
  redis:
    extends:
      file: redis.yml
      service: redis
  # elasticsearch:
  #   extends:
  #     file: elasticsearch.yml
  #     service: elasticsearch
  # minio:
  #   extends:
  #     file: minio.yml
  #     service: minio